// <auto-generated>
//     This code was generated by Refitter.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

using WebApiBootstrap.Contracts;

namespace WebApiBootstrap.Client
{
    [System.CodeDom.Compiler.GeneratedCode("Refitter", "0.9.7.0")]
    public partial interface IGetWeatherForecastEndpoint
    {
        /// <returns>OK</returns>
        /// <throws cref="ApiException">Thrown when the request returns a non-success status code.</throws>
        [Headers("Accept: application/json")]
        [Get("/weatherforecast")]
        Task<ICollection<WeatherForecast>> Execute(CancellationToken cancellationToken = default);
    }


}